MONGODB_CONFIG:
  name: 'ttalk_base_mysql' # 自定义次数据库链接名称
  type: mongodb # 数据库链接类型
  url: 'mongodb://127.0.0.1:27017' # 数据库链接地址
  username: '' # 数据库链接用户名
  password: '' # 数据库链接密码
  database: 'ttalk_base' # 数据库名
  entities: 'mongo' # 自定义加载类型
  logging: true # 数据库打印日志
  synchronize: true # 是否开启同步数据表功能

MYSQL_CONFIG:
  name: 'ttalk_base_mongo'
  type: 'mysql'
  host: 'localhost'
  port: 3306
  username: 'root'
  password: '666666'
  database: 'ttalk_base'
  entities: 'mysql' # 这里的命名一定要跟 MongoDB 里面的配置命名区分开
  synchronize: false

WECHAT_CONFIG:
  appid: 'wxf34c7842f354d984'
  secret: 'afaeade8954384bda1bac370e9a3fd5f'

JWT:
  secret: 'ttalk_base_leewei_wyq'
